Repository autowarefoundation/autoware_core, pull requests merged in 2025-08, with the labels that each got.

#593 fix(autoware_geography_utils): disable tests for egm2008-1
  .github/actions/build-and-test-differential/action.yaml
  .github/workflows/build-and-test-daily.yaml
  common/autoware_geography_utils/src/height.cpp
  common/autoware_geography_utils/test/test_height.cpp
  map/autoware_map_projection_loader/README.md
Labels: run:build-and-test-differential, run:deploy-docs

#594 fix(path_generator): avoid far goal connection
  planning/autoware_path_generator/README.md
  planning/autoware_path_generator/include/autoware/path_generator/node.hpp
  planning/autoware_path_generator/include/autoware/path_generator/utils.hpp
  planning/autoware_path_generator/media/goal_connection.drawio.svg
  planning/autoware_path_generator/src/node.cpp
  planning/autoware_path_generator/src/utils.cpp
  planning/autoware_path_generator/test/test_goal_connection.cpp
  planning/autoware_path_generator/test/test_path_cut.cpp
Labels: run:build-and-test-differential, component:planning

#600 refactor(mvp_common): add docstrings and comments
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/polygon_utils.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/utils.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/polygon_utils.cpp
Labels: run:build-and-test-differential

#563 feat(planning_test_manager): subscription callback
  testing/autoware_planning_test_manager/include/autoware/planning_test_manager/autoware_planning_test_manager.hpp
  testing/autoware_planning_test_manager/test/test_planning_test_manager.cpp
Labels: run:build-and-test-differential

#606 fix(autoware_behavior_velocity_planner_common): fix typo
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp
Labels: run:build-and-test-differential

#597 fix(autoware_motion_velocity_obstacle_stop_module): rm wrong dependency
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/package.xml
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/test/test_obstacle_stop_module_outside_check.cpp
Labels: run:build-and-test-differential, component:planning

#614 fix(autoware_behavior_velocity_planner): enable empty no_ground_pointcloud
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp
Labels: run:build-and-test-differential

#617 fix(obstacle_stop): fix bug for the backwoard motions
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/polygon_utils.cpp
Labels: run:build-and-test-differential

#622 fix(route_handler): correct handling of centerline point retrieval when requested distance is longer than lanelet length
  planning/autoware_route_handler/src/route_handler.cpp
Labels: run:build-and-test-differential

#596 fix(obstacle_stp): fix several bugs
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
Labels: run:build-and-test-differential
