Repository autowarefoundation/autoware_core, pull requests merged in 2025-09, with the labels that each got.

#615 chore(mvp_planner_common): add docstrings for PlannerData:::object
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
Labels: run:build-and-test-differential

#627 chore(autoware_marker_utils): convert hard code into function
  common/autoware_marker_utils/include/autoware/marker_utils/marker_conversion.hpp
  common/autoware_marker_utils/src/marker_conversion.cpp
Labels: run:build-and-test-differential

#628 refactor(motion_velocity_planner_common): separation of cache and polygon functions
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/utils.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/planner_data.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/utils.cpp
Labels: run:build-and-test-differential

#630 chore: jazzy-porting:fix missing header file
  common/autoware_trajectory/CMakeLists.txt
  localization/autoware_ndt_scan_matcher/package.xml
Labels: run:build-and-test-differential, porting:jazzy

#635 fix(motion_velocity_planner): fix empty point cloud header
  planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.cpp
Labels: run:build-and-test-differential, component:planning

#631 feat(motion_velocity_planner): update pointcloud preprocess
  planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
Labels: run:build-and-test-differential

#645 fix(autoware_lanelet2_utils): fix the map to pass validation
  common/autoware_lanelet2_utils/sample_map/dense_centerline/lanelet2_map.osm
Labels: run:build-and-test-differential

#638 chore(vehicle_velocity_converter): add maintainer to vehicle_velocity_converter
  sensing/autoware_vehicle_velocity_converter/package.xml
Labels: run:build-and-test-differential

#648 feat(lanelet2_utils): port message conversion from lanelet2_extension
  common/autoware_lanelet2_utils/include/autoware/lanelet2_utils/conversion.hpp
  common/autoware_lanelet2_utils/src/conversion.cpp
Labels: run:build-and-test-differential

#649 feat(lanelet2_utils): add test_case_generator and nn_search module
  common/autoware_lanelet2_utils/CMakeLists.txt
  common/autoware_lanelet2_utils/README.md
  common/autoware_lanelet2_utils/include/autoware/lanelet2_utils/nn_search.hpp
  common/autoware_lanelet2_utils/package.xml
  common/autoware_lanelet2_utils/scripts/test_case_generator.py
  common/autoware_lanelet2_utils/src/nn_search.cpp
  common/autoware_lanelet2_utils/test/nn_search.cpp
  common/autoware_lanelet2_utils/test/test_case.hpp
  common/autoware_lanelet2_utils/test_data/test_nn_search_001.yaml
  common/autoware_lanelet2_utils/test_data/test_nn_search_002.yaml
  common/autoware_lanelet2_utils/test_data/test_nn_search_003.yaml
Labels: run:build-and-test-differential, run:deploy-docs

#652 chore(gitignore): ignore node_module for prettier
  .gitignore
Labels: run:build-and-test-differential
