Repository autowarefoundation/autoware_core, pull requests merged in 2025-05, with the labels that each got.

#378 fix(route_handler): getCenterLinePath with cropping waypoints
  planning/autoware_route_handler/src/route_handler.cpp
Labels: run:build-and-test-differential

#466 docs: urls in `CHANGELOG.rst`s
  common/autoware_component_interface_specs/CHANGELOG.rst
  common/autoware_geography_utils/CHANGELOG.rst
  common/autoware_interpolation/CHANGELOG.rst
  common/autoware_kalman_filter/CHANGELOG.rst
  common/autoware_lanelet2_utils/CHANGELOG.rst
  common/autoware_motion_utils/CHANGELOG.rst
  common/autoware_object_recognition_utils/CHANGELOG.rst
  common/autoware_trajectory/CHANGELOG.rst
  common/autoware_vehicle_info_utils/CHANGELOG.rst
  localization/autoware_localization_util/CHANGELOG.rst
  map/autoware_map_loader/CHANGELOG.rst
  map/autoware_map_projection_loader/CHANGELOG.rst
  perception/autoware_ground_filter/CHANGELOG.rst
  planning/autoware_path_generator/CHANGELOG.rst
  planning/autoware_route_handler/CHANGELOG.rst
  planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/CHANGELOG.rst
  sensing/autoware_crop_box_filter/CHANGELOG.rst
  testing/autoware_pyplot/CHANGELOG.rst
  testing/autoware_test_utils/CHANGELOG.rst
Labels: run:build-and-test-differential

#457 feat(behavior_velocity_planner)!: remove unused function extendLine
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner/config/behavior_velocity_planner.param.yaml
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner/schema/behavior_velocity_planner.schema.json
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/planner_data.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/util.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp
Labels: run:build-and-test-differential

#327 feat(autoware_lanelet2_utils): refactor stop line retrieval functions into lanelet2_utils
  common/autoware_lanelet2_utils/CMakeLists.txt
  common/autoware_lanelet2_utils/include/autoware/lanelet2_utils/stop_line.hpp
  common/autoware_lanelet2_utils/media/maps/intersection/regulatory_elements.png
  common/autoware_lanelet2_utils/sample_map/intersection/regulatory_elements.osm
  common/autoware_lanelet2_utils/src/stop_line.cpp
  common/autoware_lanelet2_utils/test/stop_line.cpp
Labels: run:build-and-test-differential

#456 feat(autoware_trajectory): enhance shift flexibility
  common/autoware_trajectory/examples/example_shift.cpp
  common/autoware_trajectory/include/autoware/trajectory/point.hpp
  common/autoware_trajectory/include/autoware/trajectory/utils/shift.hpp
  common/autoware_trajectory/src/utils/shift.cpp
  common/autoware_trajectory/test/test_shift.cpp
Labels: run:build-and-test-differential

#467 fix: deprecation of .h files in message_filters
  perception/autoware_ground_filter/include/autoware/ground_filter/node.hpp
Labels: run:build-and-test-differential

#444 fix(autoware_motion_velocity_planner): fix deprecated autoware_utils header
  planning/motion_velocity_planner/autoware_motion_velocity_planner/package.xml
  planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.hpp
Labels: run:build-and-test-differential

#396 refactor(autoware_obect_recognition_utils): rewrite using modern C++ without API breakage
  common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/matching.hpp
  common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/object_classification.hpp
  common/autoware_object_recognition_utils/src/conversion.cpp
Labels: run:build-and-test-differential

#425 fix(autoware_simple_pure_pursuit): fix path follower lateral deviation
  control/autoware_simple_pure_pursuit/src/simple_pure_pursuit.cpp
Labels: run:build-and-test-differential, component:control

#435 fix(autoware_ekf_localizer): use constexpr and string_view
  localization/autoware_ekf_localizer/src/warning_message.cpp
Labels: run:build-and-test-differential, component:localization

#447 fix(autoware_planning_topic_converter): fix deprecated autoware_utils header
  planning/autoware_planning_topic_converter/package.xml
  planning/autoware_planning_topic_converter/src/path_to_trajectory.cpp
Labels: run:build-and-test-differential

#440 fix(autoware_planning_factor_interface): removed unused autoware_utils
  planning/autoware_planning_factor_interface/package.xml
Labels: run:build-and-test-differential

#442 fix(autoware_behavior_velocity_planner): fix deprecated autoware_utils header
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner/include/autoware/behavior_velocity_planner/node.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner/package.xml
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp
Labels: run:build-and-test-differential

#443 fix(autoware_motion_velocity_obstacle_stop_module): fix deprecated autoware_utils header
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/package.xml
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/parameters.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/type_alias.hpp
Labels: run:build-and-test-differential

#445 fix(autoware_motion_velocity_planner_common): fix deprecated autoware_utils header
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/collision_checker.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/plugin_module_interface.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/polygon_utils.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/utils.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/package.xml
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/collision_checker.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/planner_data.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/polygon_utils.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/utils.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/test/test_collision_checker.cpp
Labels: run:build-and-test-differential

#448 fix(autoware_objects_of_interest_marker_interface): fix deprecated autoware_utils header
  planning/autoware_objects_of_interest_marker_interface/include/autoware/objects_of_interest_marker_interface/coloring.hpp
  planning/autoware_objects_of_interest_marker_interface/include/autoware/objects_of_interest_marker_interface/marker_utils.hpp
  planning/autoware_objects_of_interest_marker_interface/package.xml
  planning/autoware_objects_of_interest_marker_interface/src/coloring.cpp
  planning/autoware_objects_of_interest_marker_interface/src/marker_utils.cpp
  planning/autoware_objects_of_interest_marker_interface/src/objects_of_interest_marker_interface.cpp
Labels: run:build-and-test-differential

#463 fix(route_handler): fix error message for the route planning failure
  planning/autoware_route_handler/src/route_handler.cpp
Labels: run:build-and-test-differential

#452 fix(autoware_motion_velocity_obstacle_stop_module): fix for mishandling lateral-distance
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/utils.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/src/utils.cpp
Labels: run:build-and-test-differential

#473 fix(autoware_simple_pure_pursuit): fix document
  control/autoware_simple_pure_pursuit/README.md
Labels: run:build-and-test-differential

#472 fix(behavior_velocity_planner_common): support overlap lane
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/arc_lane_util.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/arc_lane_util.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/test/src/test_arc_lane_util.cpp
Labels: run:build-and-test-differential

#428 feat(autoware_lanelet2_map_visualizer): porting autoware_lanelet2_map_visualizer from autoware_universe
  map/autoware_lanelet2_map_visualizer/CMakeLists.txt
  map/autoware_lanelet2_map_visualizer/README.md
  map/autoware_lanelet2_map_visualizer/launch/lanelet2_map_visualizer.launch.xml
  map/autoware_lanelet2_map_visualizer/package.xml
  map/autoware_lanelet2_map_visualizer/src/lanelet2_map_visualization_node.cpp
  map/autoware_lanelet2_map_visualizer/src/lanelet2_map_visualization_node.hpp
Labels: run:build-and-test-differential

#423 feat(port autoware_gyro_odometer): porting
  localization/autoware_gyro_odometer/CMakeLists.txt
  localization/autoware_gyro_odometer/README.md
  localization/autoware_gyro_odometer/config/gyro_odometer.param.yaml
  localization/autoware_gyro_odometer/launch/gyro_odometer.launch.xml
  localization/autoware_gyro_odometer/media/diagnostic.png
  localization/autoware_gyro_odometer/package.xml
  localization/autoware_gyro_odometer/schema/gyro_odometer.schema.json
  localization/autoware_gyro_odometer/src/gyro_odometer_core.cpp
  localization/autoware_gyro_odometer/src/gyro_odometer_core.hpp
  localization/autoware_gyro_odometer/test/test_gyro_odometer_helper.cpp
  localization/autoware_gyro_odometer/test/test_gyro_odometer_helper.hpp
  localization/autoware_gyro_odometer/test/test_gyro_odometer_pubsub.cpp
  localization/autoware_gyro_odometer/test/test_main.cpp
Labels: run:build-and-test-differential, component:localization

#474 fix(behavior_velocity_planner_common): fix argument type of findCollisionSegment
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/arc_lane_util.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/arc_lane_util.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/test/src/test_arc_lane_util.cpp
Labels: run:build-and-test-differential

#476 feat(build-and-test*): build and test on ROS 2 Jazzy too
  .github/actions/build-and-test-differential/action.yaml
  .github/workflows/build-and-test-daily.yaml
  .github/workflows/build-and-test-differential-self-hosted.yaml
  .github/workflows/build-and-test-differential.yaml
  .github/workflows/build-and-test-self-hosted.yaml
  .github/workflows/build-and-test.yaml
Labels: run:build-and-test-differential

#458 feat: add autoware_perception_objects_converter
  perception/autoware_perception_objects_converter/CMakeLists.txt
  perception/autoware_perception_objects_converter/README.md
  perception/autoware_perception_objects_converter/launch/detected_to_predicted_objects.launch.xml
  perception/autoware_perception_objects_converter/package.xml
  perception/autoware_perception_objects_converter/src/detected_to_predicted_objects_converter.cpp
  perception/autoware_perception_objects_converter/src/detected_to_predicted_objects_converter.hpp
Labels: run:build-and-test-differential, component:perception

#480 fix(path_generator): add missing autoware planning msgs
  planning/autoware_path_generator/package.xml
Labels: run:build-and-test-differential

#483 fix: tf2 uses hpp headers in rolling (and is backported)
  common/autoware_interpolation/include/autoware/interpolation/spherical_linear_interpolation.hpp
  common/autoware_motion_utils/test/src/resample/test_resample.cpp
  common/autoware_motion_utils/test/src/trajectory/benchmark_calcLateralOffset.cpp
  common/autoware_motion_utils/test/src/trajectory/test_interpolation.cpp
  common/autoware_motion_utils/test/src/trajectory/test_trajectory.cpp
  common/autoware_trajectory/examples/example_pose.cpp
  common/autoware_trajectory/examples/example_readme.cpp
  common/autoware_trajectory/src/pose.cpp
  control/autoware_simple_pure_pursuit/src/simple_pure_pursuit.cpp
  localization/autoware_ekf_localizer/include/autoware/ekf_localizer/ekf_localizer.hpp
  localization/autoware_ekf_localizer/include/autoware/ekf_localizer/ekf_module.hpp
  localization/autoware_ekf_localizer/src/ekf_module.cpp
  localization/autoware_gyro_odometer/src/gyro_odometer_core.hpp
  localization/autoware_localization_util/src/covariance_ellipse.cpp
  localization/autoware_localization_util/test/test_util_func.cpp
  localization/autoware_stop_filter/src/stop_filter.hpp
  localization/autoware_twist2accel/src/twist2accel.hpp
  perception/autoware_ground_filter/include/autoware/ground_filter/node.hpp
  planning/autoware_mission_planner/src/lanelet2_plugins/default_planner.cpp
  planning/autoware_mission_planner/src/mission_planner/arrival_checker.cpp
  planning/autoware_mission_planner/test/test_lanelet2_plugins_default_planner.cpp
  planning/autoware_route_handler/src/route_handler.cpp
  planning/autoware_velocity_smoother/include/autoware/velocity_smoother/node.hpp
  planning/autoware_velocity_smoother/include/autoware/velocity_smoother/smoother/analytical_jerk_constrained_smoother/analytical_jerk_constrained_smoother.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/trajectory_utils.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/test/src/utils.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.cpp
  sensing/autoware_gnss_poser/include/autoware/gnss_poser/gnss_poser_node.hpp
  testing/autoware_test_utils/src/autoware_test_utils.cpp
Labels: run:build-and-test-differential

#315 fix(autoware_test_utils): fix linking to yaml-cpp
  testing/autoware_test_utils/CMakeLists.txt
Labels: run:build-and-test-differential

#482 docs(path_generator): replace flowchart with raw plantuml code
  planning/autoware_path_generator/README.md
Labels: run:build-and-test-differential, run:deploy-docs

#441 fix(autoware_behavior_velocity_planner_common): fix deprecated autoware_utils header
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/arc_lane_util.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/boost_geometry_helper.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/utilization/util.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/package.xml
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/scene_module_interface.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/arc_lane_util.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/debug.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/path_utilization.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/test/src/test_trajectory_utils.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/package.xml
  planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/test/test_scene.cpp
Labels: run:build-and-test-differential

#460 feat(autoware_euclidean_cluster_object_detector): port autoware_euclidean_cluster to autoware.core
  perception/autoware_euclidean_cluster_object_detector/CMakeLists.txt
  perception/autoware_euclidean_cluster_object_detector/README.md
  perception/autoware_euclidean_cluster_object_detector/config/euclidean_cluster.param.yaml
  perception/autoware_euclidean_cluster_object_detector/config/voxel_grid_based_euclidean_cluster.param.yaml
  perception/autoware_euclidean_cluster_object_detector/include/autoware/euclidean_cluster_object_detector/euclidean_cluster.hpp
  perception/autoware_euclidean_cluster_object_detector/include/autoware/euclidean_cluster_object_detector/euclidean_cluster_interface.hpp
  perception/autoware_euclidean_cluster_object_detector/include/autoware/euclidean_cluster_object_detector/utils.hpp
  perception/autoware_euclidean_cluster_object_detector/include/autoware/euclidean_cluster_object_detector/voxel_grid_based_euclidean_cluster.hpp
  perception/autoware_euclidean_cluster_object_detector/launch/euclidean_cluster.launch.py
  perception/autoware_euclidean_cluster_object_detector/launch/euclidean_cluster.launch.xml
  perception/autoware_euclidean_cluster_object_detector/launch/voxel_grid_based_euclidean_cluster.launch.py
  perception/autoware_euclidean_cluster_object_detector/launch/voxel_grid_based_euclidean_cluster.launch.xml
  perception/autoware_euclidean_cluster_object_detector/lib/euclidean_cluster.cpp
  perception/autoware_euclidean_cluster_object_detector/lib/utils.cpp
  perception/autoware_euclidean_cluster_object_detector/lib/voxel_grid_based_euclidean_cluster.cpp
  perception/autoware_euclidean_cluster_object_detector/package.xml
  perception/autoware_euclidean_cluster_object_detector/src/euclidean_cluster_node.cpp
  perception/autoware_euclidean_cluster_object_detector/src/euclidean_cluster_node.hpp
  perception/autoware_euclidean_cluster_object_detector/src/voxel_grid_based_euclidean_cluster_node.cpp
  perception/autoware_euclidean_cluster_object_detector/src/voxel_grid_based_euclidean_cluster_node.hpp
  perception/autoware_euclidean_cluster_object_detector/test/test_voxel_grid_based_euclidean_cluster.cpp
Labels: run:build-and-test-differential, type:moving

#481 docs(simple_pure_pursuit): add flowchart
  control/autoware_simple_pure_pursuit/README.md
  control/autoware_simple_pure_pursuit/schema/simple_pure_pursuit.schema.json
Labels: run:build-and-test-differential, run:deploy-docs

#477 test(autoware_lanelet2_map_visualization): add unit test code
  map/autoware_lanelet2_map_visualizer/CMakeLists.txt
  map/autoware_lanelet2_map_visualizer/package.xml
  map/autoware_lanelet2_map_visualizer/test/lanelet2_map_visualizer_launch.test.py
  map/autoware_lanelet2_map_visualizer/test/test_lanelet2_map_visualization_node.cpp
  map/autoware_lanelet2_map_visualizer/test/test_node_initialization.cpp
Labels: run:build-and-test-differential

#446 fix(autoware_route_handler): fix deprecated autoware_utils header
  planning/autoware_route_handler/package.xml
  planning/autoware_route_handler/src/route_handler.cpp
  planning/autoware_route_handler/test/test_route_handler.cpp
Labels: run:build-and-test-differential

#373 feat(autoware_lanelet2_utils): refactor interpolation and extrapolation for lanelet2 points and line
  common/autoware_lanelet2_utils/CMakeLists.txt
  common/autoware_lanelet2_utils/include/autoware/lanelet2_utils/geometry.hpp
  common/autoware_lanelet2_utils/src/geometry.cpp
  common/autoware_lanelet2_utils/test/geometry.cpp
Labels: run:build-and-test-differential

#471 feat(vehicle_info_utils): customizable margins to vehicle footprint
  common/autoware_vehicle_info_utils/include/autoware/vehicle_info_utils/vehicle_info.hpp
  common/autoware_vehicle_info_utils/src/vehicle_info.cpp
Labels: run:build-and-test-differential

#489 chore: add autoware_tools to packages_above.repos
  packages_above.repos
Labels: run:build-and-test-differential

#492 chore: no longer support ROS 2 Galactic
  .github/workflows/deploy-docs.yaml
  common/autoware_interpolation/include/autoware/interpolation/spherical_linear_interpolation.hpp
  common/autoware_object_recognition_utils/include/autoware/object_recognition_utils/transform.hpp
  localization/autoware_localization_util/include/autoware/localization_util/util_func.hpp
  localization/autoware_localization_util/src/covariance_ellipse.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner/src/node.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/arc_lane_util.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/trajectory_utils.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/utilization/util.cpp
  sensing/autoware_gnss_poser/include/autoware/gnss_poser/gnss_poser_node.hpp
Labels: run:build-and-test-differential

#451 feat(obstacle_stop_module): maintain larger stop distance for opposing traffic
  common/autoware_motion_utils/include/autoware/motion_utils/trajectory/trajectory.hpp
  common/autoware_motion_utils/src/trajectory/trajectory.cpp
  planning/autoware_core_planning/config/motion_velocity_planner/obstacle_stop.param.yaml
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/config/obstacle_stop.param.yaml
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/parameters.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/path_length_buffer.hpp
Labels: run:build-and-test-differential

#459 feat(autoware_downsample_filters): re-implementation pointcloud downsample filters according to autoware_pointcloud_preprocessor in autoware_universe
  sensing/autoware_downsample_filters/CMakeLists.txt
  sensing/autoware_downsample_filters/README.md
  sensing/autoware_downsample_filters/config/random_downsample_filter_node.param.yaml
  sensing/autoware_downsample_filters/config/voxel_grid_downsample_filter_node.param.yaml
  sensing/autoware_downsample_filters/launch/random_downsample_filter_node.launch.xml
  sensing/autoware_downsample_filters/launch/voxel_grid_downsample_filter_node.launch.xml
  sensing/autoware_downsample_filters/package.xml
  sensing/autoware_downsample_filters/schema/random_downsample_filter_node.schema.json
  sensing/autoware_downsample_filters/schema/voxel_grid_downsample_filter_node.schema.json
  sensing/autoware_downsample_filters/src/random_downsample_filter/random_downsample_filter_node.cpp
  sensing/autoware_downsample_filters/src/random_downsample_filter/random_downsample_filter_node.hpp
  sensing/autoware_downsample_filters/src/voxel_grid_downsample_filter/faster_voxel_grid_downsample_filter.cpp
  sensing/autoware_downsample_filters/src/voxel_grid_downsample_filter/faster_voxel_grid_downsample_filter.hpp
  sensing/autoware_downsample_filters/src/voxel_grid_downsample_filter/memory.cpp
  sensing/autoware_downsample_filters/src/voxel_grid_downsample_filter/memory.hpp
  sensing/autoware_downsample_filters/src/voxel_grid_downsample_filter/transform_info.hpp
  sensing/autoware_downsample_filters/src/voxel_grid_downsample_filter/voxel_grid_downsample_filter_node.cpp
  sensing/autoware_downsample_filters/src/voxel_grid_downsample_filter/voxel_grid_downsample_filter_node.hpp
Labels: run:build-and-test-differential

#495 feat!: remove obstacle_stop_planner and obstacle_cruise_planner
  planning/autoware_planning_factor_interface/README.md
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/README.md
  testing/autoware_planning_test_manager/README.md
Labels: run:build-and-test-differential

#461 fix(path_generator): fix crop range when waypoints exist
  planning/autoware_path_generator/include/autoware/path_generator/utils.hpp
  planning/autoware_path_generator/src/node.cpp
  planning/autoware_path_generator/src/utils.cpp
Labels: run:build-and-test-differential

#487 feat: support ROS 2 Jazzy
  .github/actions/build-and-test-differential/action.yaml
  .github/workflows/build-and-test-daily.yaml
  .github/workflows/build-and-test.yaml
  .lcovrc
  common/autoware_lanelet2_utils/test/geometry.cpp
  common/autoware_trajectory/CMakeLists.txt
  common/autoware_trajectory/package.xml
  localization/autoware_ekf_localizer/src/ekf_localizer.cpp
  localization/autoware_gyro_odometer/test/test_gyro_odometer_pubsub.cpp
  map/autoware_map_loader/src/lanelet2_map_loader/lanelet2_map_loader_node.cpp
  perception/autoware_euclidean_cluster_object_detector/lib/voxel_grid_based_euclidean_cluster.cpp
  testing/autoware_pyplot/CMakeLists.txt
  testing/autoware_pyplot/package.xml
Labels: run:build-and-test-differential

#498 chore(autoware_test_utils): delete `launch` directory to remove dependency on `autoware_launch`
  testing/autoware_test_utils/CMakeLists.txt
  testing/autoware_test_utils/launch/psim_intersection.launch.xml
  testing/autoware_test_utils/launch/psim_road_shoulder.launch.xml
Labels: run:build-and-test-differential

#505 feat(autoware_motion_velocity_planner)!: only wait for the required subscriptions
  planning/motion_velocity_planner/autoware_motion_velocity_obstacle_stop_module/src/obstacle_stop_module.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner/src/node.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner/src/planner_manager.cpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner/src/planner_manager.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/planner_data.hpp
  planning/motion_velocity_planner/autoware_motion_velocity_planner_common/include/autoware/motion_velocity_planner_common/plugin_module_interface.hpp
Labels: run:build-and-test-differential

#504 feat(behavior_velocity_planner_common, stop_line_module): print module/regulatory_element/lane/line ID and improve stop line module log
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/include/autoware/behavior_velocity_planner_common/scene_module_interface.hpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_planner_common/src/scene_module_interface.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.cpp
  planning/behavior_velocity_planner/autoware_behavior_velocity_stop_line_module/src/scene.hpp
Labels: run:build-and-test-differential
